services:

  preprocessing-service:
    image: preprocessing
    environment:
      ENVIRONMENT: "CLOUD"
    volumes:
      - ./shared/inputs:/app/shared/inputs
      - shared-processed:/app/shared/processed
    entrypoint: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - app-network
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://preprocessing-service:8000/preprocess/healthcheck || exit 1"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  analyse-qualite-service:
    image: analysequalite
    volumes:
      - shared-processed:/app/shared/processed
    entrypoint: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://analyse-qualite-service:8000/quality_analysis/healthcheck || exit 1"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  transcription-audio-service:
    image: audiotranscription
    volumes:
      - shared-processed:/app/shared/processed
    entrypoint: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://transcription-audio-service:8000/transcribe/healthcheck || exit 1"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  generation-resume-service:
    image: generationresume
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all 
    volumes:
      - shared-processed:/app/shared/processed
    entrypoint: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://generation-resume-service:8000/generate_summary/healthcheck || exit 1"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  csv-generation-service:
    image: excelgeneration
    volumes:
      - shared-processed:/app/shared/processed
      - ./shared/outputs:/app/shared/outputs
    entrypoint: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - app-network
    depends_on:
      preprocessing-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://csv-generation-service:8000/generate-xlsx/healthcheck || exit 1"]
      interval: 1m30s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  shared-inputs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  shared-processed:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  shared-outputs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
