apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: analyse-qualite-service
  name: analyse-qualite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: analyse-qualite-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: analyse-qualite-service
    spec:
      containers:
        - command:
            - uvicorn
            - api:app
            - --host
            - 0.0.0.0
            - --port
            - "8001"
          image: analysequalite
          livenessProbe:
            exec:
              command:
                - curl -f http://analyse-qualite-service:8001/quality_analysis/healthcheck || exit 1
            failureThreshold: 3
            periodSeconds: 90
            timeoutSeconds: 5
          name: analyse-qualite-service
          ports:
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - mountPath: /app/shared/processed
              name: shared-processed
      restartPolicy: Always
      volumes:
        - name: shared-processed
          persistentVolumeClaim:
            claimName: shared-processed
