apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: csv-generation-service
  name: csv-generation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: csv-generation-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: csv-generation-service
    spec:
      containers:
        - command:
            - uvicorn
            - api:app
            - --host
            - 0.0.0.0
            - --port
            - "8004"
          image: excelgeneration
          livenessProbe:
            exec:
              command:
                - curl -f http://csv-generation-service:8004/generate-xlsx/healthcheck || exit 1
            failureThreshold: 3
            periodSeconds: 90
            timeoutSeconds: 5
          name: csv-generation-service
          ports:
            - containerPort: 8004
              protocol: TCP
          volumeMounts:
            - mountPath: /app/shared/processed
              name: shared-processed
            - mountPath: /app/shared/outputs
              name: shared-outputs
      restartPolicy: Always
      volumes:
        - name: shared-processed
          persistentVolumeClaim:
            claimName: shared-processed
        - name: shared-outputs
          persistentVolumeClaim:
            claimName: shared-outputs
