apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: generation-resume-service
  name: generation-resume-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: generation-resume-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: generation-resume-service
    spec:
      containers:
        - command:
            - uvicorn
            - api:app
            - --host
            - 0.0.0.0
            - --port
            - "8003"
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
          image: generationresume
          livenessProbe:
            exec:
              command:
                - curl -f http://generation-resume-service:8003/generate_summary/healthcheck || exit 1
            failureThreshold: 3
            periodSeconds: 90
            timeoutSeconds: 5
          name: generation-resume-service
          ports:
            - containerPort: 8003
              protocol: TCP
          volumeMounts:
            - mountPath: /app/shared/processed
              name: shared-processed
      restartPolicy: Always
      volumes:
        - name: shared-processed
          persistentVolumeClaim:
            claimName: shared-processed
