apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: shared-processed
  name: shared-processed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
