apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: shared-outputs
  name: shared-outputs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
