apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.sharedVolumes.inputs }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sharedVolumes.inputs.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.sharedVolumes.outputs }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sharedVolumes.outputs.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.sharedVolumes.processed }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sharedVolumes.processed.size }}
---
