name: Test Analyse Qualité

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Récupère le dépôt GitHub
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'  # Version de Python à utiliser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances via le fichier requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings  # Exécute pytest et arrête au premier test échoué
